name: myenv
channels:
  - defaults
dependencies:
  - python=3.10.13
  - ipywidgets=7.7.1
  - jupyterlab-manager=5.0.10
  - nodejs=20.12.1
  - numpy=1.24.2
  - pandas=1.5.3
  - tqdm=4.64.0
  - fileupload
  - openpyxl
